# Generated by Django 5.2.14 on 2026-07-25 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0004_order_invoice_number_order_pdf_file_order_subtotal_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='image_file',
            field=models.FileField(blank=True, null=True, upload_to='invoices_images/'),
        ),
    ]
