# Generated by Django 5.2.15 on 2026-06-09 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='barcode_id',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
