# Generated by Django 5.2.14 on 2026-07-21 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_managedproduct'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchase',
            name='product',
        ),
        migrations.AddField(
            model_name='purchase',
            name='product_name',
            field=models.CharField(default='-', max_length=200),
        ),
    ]
