# Generated by Django 5.2.16 on 2026-09-11 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0012_productvariant_barcode_productvariant_buying_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='purchase_qty',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='product',
            name='sale_qty',
            field=models.IntegerField(default=0),
        ),
    ]
