# Generated by Django 5.2.16 on 2026-09-12 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0013_product_purchase_qty_product_sale_qty'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productvariant',
            name='barcode',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
